AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "lib/juicycop.rb"
    - "Guardfile"
    - "Rakefile"
    - "vendor/bundle/**/*"

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20
